name: onboarding
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2  #gallery phone
  universal_io: ^2.0.4 #platform specific stuff
  sliding_up_panel: ^2.0.0+1
  salomon_bottom_bar: ^3.3.1
  navigation_history_observer: ^1.1.1
  http_parser: ^4.0.0
  shared_preferences: ^2.0.15
  file_picker: ^8.1.4 #gallery web
  lottie: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/analysing.json
    - assets/animations/inspect.json
